### ISSUE TITLE
"Attempting to decrypt but no vault secrets found"

### ISSUE THREAD

**Issue by Alexander-Giaquinto** [aminvakil/lamp#3]
This does not work.

**Comment by aminvakil** [comment]
There are some vaults in repository like
https://github.com/aminvakil/lamp/blob/main/roles/mysql_initial/defaults/vault.yml
which are encrypted with a simple password which is available here
https://github.com/aminvakil/lamp/blob/main/vault.pw

You can test decrypting them with `--vault-password-file vault.pw`.

But at last you should re-key your vaults with another password with `ansible-vault rekey your_vault` and edit them to your needs with `ansible-vault edit your_vault`.
